[package]
name = "litex-pac"
version = "0.1.0"
authors = ["Vadim Kaushan <admin@disasm.info>"]
edition = "2018"

[build-dependencies]
svd2ral = { path = "../svd2ral" }

[dependencies]
cortex-m = "0.6.4"
